### ISSUE TITLE
User profile page should show the user their username

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/photic#125]

**Comment by joefutrelle** [comment]
and full name. eventually we'll put stats there, or maybe have them in a separate stats UI

**Comment by kaimikacolin** [comment]
![Screen Shot 2021-04-29 at 1 22 19 PM](https://user-images.githubusercontent.com/65564591/116607229-f457a700-a8ee-11eb-835a-23f46264bb12.png)

**Comment by kaimikacolin** [comment]
Is there anything else that I should add here? I could get started on stats if you have any in mind.

**Comment by kaimikacolin** [comment]
![Screen Shot 2021-05-04 at 12 59 30 PM](https://user-images.githubusercontent.com/65564591/117055692-a836a900-acd8-11eb-9db7-0e82e9ca4207.png)

**Comment by joefutrelle** [comment]
I like this. I just tried it out and found a bug: if the user hasn't made any annotations, it crashes trying to find the last annotation.

**Comment by kaimikacolin** [comment]
@joefutrelle Bug Fixed - Any other items we could add here?
