### ISSUE TITLE
Bug - ISIIS ROIs displayed twice when sorting by size

### ISSUE THREAD

**Issue by eepeacock** [WHOIGit/photic#145]
Jonathan Nash testing/using PHOTIC with ISIIS ROIs has found that he is seeing double. Some of the ROIs will appear twice, not even right next to each other. 

When sorting by ROI number, this problem does not show up.

**Comment by joefutrelle** [comment]
How can I reproduce this issue?

**Comment by joefutrelle** [comment]
could be related to #146

**Comment by mike-kaimika** [comment]
@joefutrelle I think we determined previously that this more about the loading of the ROIs than the UI, correct? The duplicates that I had found had very slight differences in the heights, and the IDs were different even though the image "looked" the same
