### ISSUE TITLE
Feature request - sort by ROI number after sorting by size

### ISSUE THREAD

**Issue by eepeacock** [WHOIGit/photic#146]
When sorting by size, with a large number of ISIIS ROIs, Jonathan found that every time the page is refreshed, all of the ROIs of the same height do a big shuffle. This is really problematic if a bunch of work has been done already. We were thinking maybe we could implement sort by ROI number after sort by size. Does that make sense? 

We were also thinking maybe this would negate the bug of ROIs appearing in double when sorting by size - but, thought it best to report that bug anyway.

**Comment by joefutrelle** [comment]
Yes, this can be fixed in the way you suggest--sorting by ROI number after sorting by size.

**Comment by joefutrelle** [comment]
I can take this one.
