### ISSUE TITLE
Ability to skip forward n ROIs in current view

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/photic#154]
> Would it be possible to select the start ROI for display (useful for cases where there are 1000s and we want to resume the task part way in without paging down over and over and over...)

**Comment by mike-kaimika** [comment]
@joefutrelle Assigning you temporarily to see if the local storage option I suggested earlier today would work for Heidi

**Comment by kaimikacolin** [comment]
Also add Page Numbers and Page Dividers, and improve feel of infinite scroll
