### ISSUE TITLE
Add skeleton loaders for images

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/photic#192]
Ideally these skeleton loaders should be the dimensions of the ROIs and laid out the same way, so that the ROIs load into the skeleton loaders "in place", if that makes sense.

We'd need to return image dimensions from the roi_list endpoint.

**Comment by mike-kaimika** [comment]
Issue closed for now; the recent upgrades to the underlying VM have increased the performance to an acceptable level. If future work is needed, new tickets will be created
