### ISSUE TITLE
Speed up roi_list endpoint and sorting/paging

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/photic#193]
The query determining which ROIs belong to a given image collection and label is slow, and may be able to be optimized. In addition the endpoint is called repeatedly, once for each page, multiplying the slowdown.

roi_list should return a JSON which contains for each image:
* the "roi_id" (not the "id" column but the "roi_id" column)
* the height of the image
* the path of the image

sorting and pagination can be done on the client side, or alternatively the entire query result could be cached on the backend to support sorting and pagination. other approaches may also provide a speedup.

**Comment by mike-kaimika** [comment]
Issue closed for now; the recent upgrades to the underlying VM have increased the performance to an acceptable level. If future work is needed, new tickets will be created
