### ISSUE TITLE
Implement annotating images

### ISSUE THREAD

**Issue by mike-kaimika** [WHOIGit/photic#50]
Users can currently select images from within the UI. The next steps is to allow those selected images to be annotated based on the label selected in the "assign label" area on the left sidebar. Additional notes from our recent discussion:

- Under the dropdown, add a checkbox for "hide", unchecked by default. If checked off, once the user assigns an annotation to an image(s), it will remove the image from the DOM immediately. If unchecked, it will remain
- Future iterations will improve this based on filtering, ajax calls, etc, but this that is a target for a later version
- Images should be annotated based on the user that is logged into the system
- Verify that once the annotation is done, if the user elected not to hide the image, right clicking and seeing the annotation list should show the one that was just added
- Make sure after clicking "apply" the page does not refresh (it does now, but likely just due to it not being implemented yet)
- If the user wants to refresh the list, they will need to specifically click on the "filter" button to do so; nothing automatic at this time

**Comment by joefutrelle** [comment]
To your point about the right clicking, no code changes will be required because it's already an AJAX call.
