### ISSUE TITLE
Adding a label does not provide user feedback to indicate success or failure

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/photic#60]

**Comment by mike-kaimika** [comment]
@MattCharron32 Assigned you as well to help determine what the feedback should look like

**Comment by joefutrelle** [comment]
"Failure" would be if the label already exists, or is formatted wrong--this could be done during validation of the input.

Not sure what "success" should look like beyond a dismissable notification (same place as "n rois found"). I think a typical use case for adding a label is that the user wants to split a category into finer categories, so success might look like populating the "assign label" dropdown with the new label, but that should be an optional checkbox called "Use new label" or something.

**Comment by joefutrelle** [comment]
For v1a it could just be a modal.

**Comment by joefutrelle** [comment]
remove the "test_label" that's filled in initially in the text entry box
